theme: minima
title: Learning and Play
author: tracywong117
email: tracywong117@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Wanting to be someone else is a waste of the person you are.
# social links
github_username:  tracywong117 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
